baseURL = "http://sasaba.net"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "sasaba 的博客"
theme = "dream"
disqusShortname = "sasaba"

enableRobotsTXT = true
hasCJKLanguage = true

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
    background = "#ccc"
    backgroundImage = "/me/background.jpg"
    linkColor = "seagreen"

    # dark mode
    # defaultDark = true
    backgroundDark = "black"
    backgroundImageDark = "/me/background-dark.jpg"
    darkLinkColor = "darkseagreen"
    darkNav = true
    dark404 = true


    author = "sasaba"
    description = "sasaba 的技术、生活记录。"
    avatar = "/me/sasaba.jpg"
    headerTitle = "sasaba 的博客"
    motto = "蛾眉中划三千丈，不著人间半点愁。"
    categoriesLimitInHeader = 6

    rss = true
    email = "wang918562230@qq.com"
    github = "ssbeatty"

    # twitter = "g1eny0ung"
    # facebook = "g1eny0ung"
    # instagram = "g1eny0ung"
    # mastodon = ""
    # linkedin = "g1eny0ung"
    # stackoverflow = "5676489/g1eny0ung"
    # codepen = "g1eny0ung"

    # siteStartYear = 2016

    favicon = "/favicon.ico"


    highlightjs = true
    # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
    highlightjsExtraLanguages = ["ocaml"]
    highlightjsTheme = "vs"
    highlightjsThemeDark = "monokai-sublime"

    # search
    enableSearch = false

    # options
    showSummaryCoverInPost = true

[params.advanced]
    customCSS = ["css/custom.css"]
    customJS = ["js/baidu.js"]